-- Generated from catalog/anno117-community-2.1-c6a6e752.json. Do not edit by hand.
return {
    release_id = "anno117-community-2.1-c6a6e752",
    source_hash = "5913d65b9d6bd2b55b78858a40db1fde3d6bbae2a7c57fdf39f95f84a0a252cc",
    products = {
        { guid = 31700, name = "Amphorae" },
        { guid = 13810, name = "Armour" },
        { guid = 2093, name = "Barley" },
        { guid = 31702, name = "Beavers" },
        { guid = 2154, name = "Beer" },
        { guid = 2133, name = "Bird Tongues" },
        { guid = 2155, name = "Bird Tongues in Aspic" },
        { guid = 2137, name = "Bread" },
        { guid = 2127, name = "Bronze" },
        { guid = 2156, name = "Brooches" },
        { guid = 8558, name = "Caviar" },
        { guid = 2126, name = "Celtic Green" },
        { guid = 2163, name = "Chariots" },
        { guid = 2128, name = "Chassis" },
        { guid = 2153, name = "Cheese" },
        { guid = 31706, name = "Clan Shields" },
        { guid = 2086, name = "Clay" },
        { guid = 2161, name = "Cloaks" },
        { guid = 2121, name = "Cloth" },
        { guid = 2085, name = "Coal" },
        { guid = 2097, name = "Cockles" },
        { guid = 2178, name = "Concrete" },
        { guid = 2099, name = "Copper Ore" },
        { guid = 8562, name = "Cushions" },
        { guid = 55954, name = "Drinking Horns" },
        { guid = 2094, name = "Dye Plants" },
        { guid = 2108, name = "Eels" },
        { guid = 2151, name = "Fine Glass" },
        { guid = 2063, name = "Flax" },
        { guid = 2119, name = "Flour" },
        { guid = 31707, name = "Fur Hats" },
        { guid = 2139, name = "Garum" },
        { guid = 2117, name = "Glass" },
        { guid = 31698, name = "Gold" },
        { guid = 31697, name = "Gold Ore" },
        { guid = 31709, name = "Granite" },
        { guid = 2101, name = "Granite Block" },
        { guid = 2070, name = "Grapes" },
        { guid = 2162, name = "Handmirrors" },
        { guid = 31704, name = "Head Piece" },
        { guid = 31694, name = "Hemp" },
        { guid = 31701, name = "Herbs" },
        { guid = 2076, name = "Honeycombs" },
        { guid = 2075, name = "Horses" },
        { guid = 2115, name = "Iron" },
        { guid = 2080, name = "Iron Ore" },
        { guid = 2132, name = "Lard" },
        { guid = 145221, name = "Latrunculi Sets" },
        { guid = 2071, name = "Lavender" },
        { guid = 2110, name = "Leather" },
        { guid = 2078, name = "Limestone" },
        { guid = 2147, name = "Loungers" },
        { guid = 2089, name = "Mackerel" },
        { guid = 2131, name = "Malt" },
        { guid = 2179, name = "Marble" },
        { guid = 8563, name = "Minerals" },
        { guid = 2152, name = "Mosaics" },
        { guid = 2102, name = "Mud" },
        { guid = 3158, name = "Murex Snails" },
        { guid = 2146, name = "Necklaces" },
        { guid = 2068, name = "Oats" },
        { guid = 145102, name = "Obsidian" },
        { guid = 2105, name = "Ochs" },
        { guid = 2149, name = "Olive Oil" },
        { guid = 2072, name = "Olives" },
        { guid = 2123, name = "Ornate Wood" },
        { guid = 2112, name = "Oysters" },
        { guid = 2140, name = "Oysters with Caviar" },
        { guid = 2124, name = "Pigments" },
        { guid = 2074, name = "Pigs" },
        { guid = 2142, name = "Pileus" },
        { guid = 8404, name = "Ponies" },
        { guid = 2136, name = "Porridge" },
        { guid = 2159, name = "Reed Shoes" },
        { guid = 2103, name = "Reeds" },
        { guid = 31695, name = "Resin" },
        { guid = 31768, name = "Roast Beef" },
        { guid = 2171, name = "Rope" },
        { guid = 2172, name = "Sails" },
        { guid = 2090, name = "Salt" },
        { guid = 31703, name = "Saltwash" },
        { guid = 7985, name = "Saltwort" },
        { guid = 2144, name = "Sandals" },
        { guid = 8561, name = "Sandarac Wood" },
        { guid = 2088, name = "Sardines" },
        { guid = 8405, name = "Sausages" },
        { guid = 8420, name = "Seashells" },
        { guid = 2073, name = "Sheep" },
        { guid = 2091, name = "Silica" },
        { guid = 2129, name = "Silver" },
        { guid = 2079, name = "Silver Ore" },
        { guid = 2106, name = "Small Birds" },
        { guid = 2143, name = "Soap" },
        { guid = 2166, name = "Standing Lyres" },
        { guid = 145220, name = "Statuettes" },
        { guid = 2135, name = "String" },
        { guid = 2087, name = "Sturgeon" },
        { guid = 2176, name = "Tiles" },
        { guid = 2174, name = "Timber" },
        { guid = 2100, name = "Tin Ore" },
        { guid = 2145, name = "Togas" },
        { guid = 2157, name = "Torcs" },
        { guid = 2158, name = "Trousers" },
        { guid = 2141, name = "Tunics" },
        { guid = 2180, name = "Tyrian Purple" },
        { guid = 2084, name = "Uncut Marble" },
        { guid = 2169, name = "Wattle & Daub" },
        { guid = 2173, name = "Weapons" },
        { guid = 2069, name = "Wheat" },
        { guid = 31708, name = "Wigs" },
        { guid = 2138, name = "Wine" },
        { guid = 2077, name = "Wood" },
        { guid = 2150, name = "Writing Tablets" },
    },
    buildings = {
        { guid = 2795, name = "Apiary" },
        { guid = 8427, name = "Apiary" },
        { guid = 13808, name = "Armourer" },
        { guid = 55945, name = "Armourer" },
        { guid = 3174, name = "Bakery" },
        { guid = 5960, name = "Bakery" },
        { guid = 2799, name = "Barley Farm" },
        { guid = 31770, name = "Beaver Hatter" },
        { guid = 31759, name = "Beaver Trapper" },
        { guid = 5851, name = "Bird Charmer" },
        { guid = 5614, name = "Birrus Stitcher" },
        { guid = 5570, name = "Brewery" },
        { guid = 5470, name = "Bronze Smelter" },
        { guid = 145229, name = "Caelator" },
        { guid = 3198, name = "Chair Maker" },
        { guid = 2880, name = "Charcoal Burner" },
        { guid = 5977, name = "Charcoal Burner" },
        { guid = 5616, name = "Chariot Workshop" },
        { guid = 5611, name = "Chassis Builder" },
        { guid = 2970, name = "Clay Pit" },
        { guid = 144810, name = "Coal Mine" },
        { guid = 144811, name = "Coal Mine" },
        { guid = 5278, name = "Cockle Picker" },
        { guid = 3129, name = "Concrete Mixer" },
        { guid = 5946, name = "Concrete Mixer" },
        { guid = 5290, name = "Copper Mine" },
        { guid = 8887, name = "Cushion Stuffer" },
        { guid = 6586, name = "Dairy" },
        { guid = 5967, name = "Donkey Mill" },
        { guid = 2999, name = "Dye Works" },
        { guid = 31767, name = "Earth Oven" },
        { guid = 5299, name = "Eel Grabber" },
        { guid = 5604, name = "Epicure of Air" },
        { guid = 3186, name = "Epicure of Water" },
        { guid = 5605, name = "Fibularium" },
        { guid = 8893, name = "Fish Gutter" },
        { guid = 2955, name = "Fishing Hut" },
        { guid = 2669, name = "Flax Farm" },
        { guid = 5971, name = "Flax Farm" },
        { guid = 3070, name = "Furnace" },
        { guid = 5969, name = "Furnace" },
        { guid = 3185, name = "Garum Works" },
        { guid = 3081, name = "Gilder" },
        { guid = 3074, name = "Glass Smelter" },
        { guid = 3202, name = "Glassblower" },
        { guid = 50280, name = "Gold Mine" },
        { guid = 31753, name = "Gold Washer" },
        { guid = 31755, name = "Goldsmith" },
        { guid = 3075, name = "Grain Mill" },
        { guid = 41811, name = "Granite Cutter" },
        { guid = 5295, name = "Granite Quarry" },
        { guid = 5469, name = "Greenhands" },
        { guid = 31766, name = "Headpiece Maker" },
        { guid = 31750, name = "Hemp Farm" },
        { guid = 31762, name = "Hemp Farm" },
        { guid = 31764, name = "Herb Garden" },
        { guid = 55963, name = "Horner" },
        { guid = 15514, name = "Horse Breeder" },
        { guid = 2794, name = "Horse Breeder" },
        { guid = 5975, name = "Horsecatcher" },
        { guid = 5608, name = "Hosier" },
        { guid = 2918, name = "Iron Mine" },
        { guid = 5982, name = "Iron Mine" },
        { guid = 3192, name = "Jeweller" },
        { guid = 5935, name = "Labourer's Yard" },
        { guid = 145230, name = "Latrunculi Workshop" },
        { guid = 2698, name = "Lavender Grower" },
        { guid = 2916, name = "Limestone Quarry" },
        { guid = 5978, name = "Limestone Quarry" },
        { guid = 3191, name = "Loom Weavery" },
        { guid = 4832, name = "Lythier" },
        { guid = 5474, name = "Malthouse" },
        { guid = 3138, name = "Marble Mason" },
        { guid = 2954, name = "Marble Quarry" },
        { guid = 3082, name = "Mineral Crusher" },
        { guid = 2920, name = "Mineral Quarry" },
        { guid = 5848, name = "Mud Drier" },
        { guid = 5615, name = "Narcissium" },
        { guid = 2200, name = "Oat Farm" },
        { guid = 5847, name = "Ochs Farm" },
        { guid = 2699, name = "Olive Grower" },
        { guid = 4831, name = "Olive Press" },
        { guid = 8586, name = "Oyster Bed" },
        { guid = 2793, name = "Pig Farm" },
        { guid = 5974, name = "Pig Farm" },
        { guid = 3188, name = "Pileus Felter" },
        { guid = 3171, name = "Porridge Stand" },
        { guid = 3199, name = "Potter" },
        { guid = 55962, name = "Potter" },
        { guid = 5849, name = "Reed Gatherer" },
        { guid = 31756, name = "Renderer" },
        { guid = 5475, name = "Renderer" },
        { guid = 31752, name = "Resin Tapper" },
        { guid = 31761, name = "Resin Tapper" },
        { guid = 3168, name = "Ropemaker" },
        { guid = 5956, name = "Ropemaker" },
        { guid = 3169, name = "Sailmaker" },
        { guid = 5955, name = "Sailmaker" },
        { guid = 5959, name = "Salsicium" },
        { guid = 2957, name = "Salt Ponds" },
        { guid = 31772, name = "Saltwort Burner" },
        { guid = 2796, name = "Saltwort Picker" },
        { guid = 10929, name = "Sand Refinery" },
        { guid = 2958, name = "Sand Refinery" },
        { guid = 3190, name = "Sandal Maker" },
        { guid = 8579, name = "Sandarac Nursery" },
        { guid = 3089, name = "Sawmill" },
        { guid = 5945, name = "Sawmill" },
        { guid = 2956, name = "Scomber's Shack" },
        { guid = 2786, name = "Sheep Farm" },
        { guid = 5973, name = "Sheep Farm" },
        { guid = 8431, name = "Shell Gatherer" },
        { guid = 31773, name = "Shieldbeater" },
        { guid = 5609, name = "Shoe Weaver" },
        { guid = 5472, name = "Silver Forge" },
        { guid = 5980, name = "Silver Mine" },
        { guid = 8580, name = "Snailery" },
        { guid = 3189, name = "Soap Maker" },
        { guid = 3187, name = "Spinner" },
        { guid = 5958, name = "Spinner" },
        { guid = 5481, name = "Stringer" },
        { guid = 2971, name = "Sturgeon Hatchery" },
        { guid = 3201, name = "Tabulus" },
        { guid = 2994, name = "Tannery" },
        { guid = 80612, name = "Tannery" },
        { guid = 3203, name = "Tessera Works" },
        { guid = 3091, name = "Tiler" },
        { guid = 5947, name = "Tiler" },
        { guid = 5291, name = "Tin Mine" },
        { guid = 5477, name = "Tongue Plucker" },
        { guid = 23723, name = "Vineyard" },
        { guid = 2694, name = "Vineyard" },
        { guid = 23753, name = "Vintner" },
        { guid = 3177, name = "Vintner" },
        { guid = 3170, name = "Weaponsmith" },
        { guid = 5954, name = "Weaponsmith" },
        { guid = 3079, name = "Weaver" },
        { guid = 2800, name = "Weld Crop" },
        { guid = 2693, name = "Wheat Farm" },
        { guid = 5972, name = "Wheat Farm" },
        { guid = 31769, name = "Wig Maker" },
        { guid = 5606, name = "Wire-Twister" },
        { guid = 2878, name = "Woodcutter" },
        { guid = 5976, name = "Woodcutter" },
    },
    regions = {
        { guid = 3225, session_guid = 3245, name = "Latium" },
        { guid = 6626, session_guid = 6627, name = "Albion" },
        { guid = 37136, session_guid = 37135, name = "Region Worldmap" },
    },
}
